const TODO_SEARCHED = "TODO_SEARCHED";
const TODO_SEARCH = "TODO_SEARCH";
const TODO_CLEAR = "TODO_CLEAR";
const TODO_REMOVE = "TODO_REMOVE";
const TODO_ADD = "TODO_ADD";
const TODO_ADDED = "TODO_ADDED";
const DESCRIPTION_CHANGED = "DESCRIPTION_CHANGED";
const TODO_MARKED_AS_DONE = "TODO_MARKED_AS_DONE";
const TODO_MARK_AS_DONE = "TODO_MARK_AS_DONE";
const TODO_MARKED_AS_PENDING = "TODO_MARKED_AS_PENDING";
const TODO_MARK_AS_PENDING = "TODO_MARK_AS_PENDING";
const ACTIONS = {
  TODO_SEARCHED,
  TODO_SEARCH,
  TODO_CLEAR,
  TODO_REMOVE,
  TODO_ADDED,
  TODO_ADD,
  DESCRIPTION_CHANGED,
  TODO_MARKED_AS_DONE,
  TODO_MARK_AS_DONE,
  TODO_MARK_AS_PENDING,
  TODO_MARKED_AS_PENDING
};

export default ACTIONS;
